### ISSUE TITLE
english grammar, not error/bug/issue

### ISSUE THREAD

**Issue by acarsy01** [efekoca/php-mail-sender#1]
```html
Your e-mail host adress: <input type = "text" class = "inp" name = "hosturl" required> <br>
```
to
```html
Your e-mail host address: <input type = "text" class = "inp" name = "hosturl" required> <br>
```
in
[index.js#L80](https://github.com/efekoca/php-mail-sender/blob/master/index.php#L80)

[index.js#L77](https://github.com/efekoca/php-mail-sender/blob/master/index.php#L77) You can write this in more readable format.

also i liked this, thx

**Comment by acarsy01** [comment]
@efekoca

**Comment by snowy1000** [comment]
Just to clarify, this is not where feedback sent to. In fact, there is nowhere like that.
Also if it's not an "error/bug/issue", why you send this ticket over Issues? Create a pull request to request merging of your own branch to master.
Third thing is you don't need to mention anyone, we'll look onto it when possible.
And if you really mind grammar, "english" starts with capital letter.

Please care.
